### ISSUE TITLE
Nesting of <View> within <Text> is not supported on Android.

### ISSUE THREAD

**Issue by santosh-btc** [Gil2015/react-native-table-component#1]
my code

```
{
    busBarData.map((data, i) => (
        <Row key={i} data={data.map((cell, i) => 
        <Cell key={i} data={cell} height={28} style={{backgroundColor: (new ValidationManager()).voltageValidator(cell)}} textStyle={styles.text}/>)} flexArr={[1,1, 1]} style={styles.row} />
    ))
}
```
![device-2017-06-15-165133](https://user-images.githubusercontent.com/14067724/27179175-08a8cbc6-51eb-11e7-912b-247875bcd8b3.png)
 Please Suggest...

**Comment by Gil2015** [comment]
The row component already contains the text component, which cannot be nested in the cell.
U can use tableWraper or view instead of row.
Or use it like that：
        `<Rows key={i} data={busBarData} flexArr={[1, 1, 1]} style={styles.row} />`
