### ISSUE TITLE
How to remove the border outside,keep boder line in table.

### ISSUE THREAD

**Issue by zuijiusi** [Gil2015/react-native-table-component#103]
![图片](https://user-images.githubusercontent.com/17403481/67925598-cfe21800-fbee-11e9-93b3-754389176536.png)
export default class ExampleTwo extends Component {
  constructor(props) {
    super(props);
    this.state = {
      tableHead: ['', '目标', '达成', '完成率'],
      tableTitle: ['大客户销售部', '海外销售部', '渠道销售部', '软件销售部', '网商部',"合计"],
      tableData: [
        ['￥10,000,000', '￥10,000,000', '100%'],
        ['￥15,000,000', '￥15,000,000', '100%'],
        ['￥20,000,000', '￥20,000,000', '100%'],
        ['￥4,000,000', '￥4,000,000', '100%'],
        ['￥8,000,000', '￥8,000,000', '100%'],
        ['￥57,000,000', '￥57,000,000', '100%'],
      ]
    }
  }

  render() {
    const state = this.state;
    return (
      <View style={styles.container}>
        <Table borderStyle={{borderWidth: 0.5,borderColor: 'transparent'}}>
          <Row data={state.tableHead} flexArr={[2, 2,2,1]} style={styles.head} textStyle={styles.text}/>
          <TableWrapper style={styles.wrapper}>
            <Col data={state.tableTitle} style={styles.title} heightArr={[28,28]} textStyle={styles.text}/>
            <Rows data={state.tableData} flexArr={[1, 1,0.5]} style={styles.row} textStyle={styles.text}/>
          </TableWrapper>
        </Table>
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: { flex: 1, paddingTop: 30, backgroundColor: '#fff' },
  head: {  height: 40,  backgroundColor: '#f1f8ff'  },
  wrapper: { flexDirection: 'row',},
  title: { flex: 1, borderWidth: 0.3 },
  row: {  height: 28 ,borderWidth: 0.3  },
  text: { textAlign: 'center' }
});export default class ExampleTwo extends Component {
  constructor(props) {
    super(props);
    this.state = {
      tableHead: ['', '目标', '达成', '完成率'],
      tableTitle: ['大客户销售部', '海外销售部', '渠道销售部', '软件销售部', '网商部',"合计"],
      tableData: [
        ['￥10,000,000', '￥10,000,000', '100%'],
        ['￥15,000,000', '￥15,000,000', '100%'],
        ['￥20,000,000', '￥20,000,000', '100%'],
        ['￥4,000,000', '￥4,000,000', '100%'],
        ['￥8,000,000', '￥8,000,000', '100%'],
        ['￥57,000,000', '￥57,000,000', '100%'],
      ]
    }
  }

  render() {
    const state = this.state;
    return (
      <View style={styles.container}>
        <Table borderStyle={{borderWidth: 0.5,borderColor: 'transparent'}}>
          <Row data={state.tableHead} flexArr={[2, 2,2,1]} style={styles.head} textStyle={styles.text}/>
          <TableWrapper style={styles.wrapper}>
            <Col data={state.tableTitle} style={styles.title} heightArr={[28,28]} textStyle={styles.text}/>
            <Rows data={state.tableData} flexArr={[1, 1,0.5]} style={styles.row} textStyle={styles.text}/>
          </TableWrapper>
        </Table>
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: { flex: 1, paddingTop: 30, backgroundColor: '#fff' },
  head: {  height: 40,  backgroundColor: '#f1f8ff'  },
  wrapper: { flexDirection: 'row',},
  title: { flex: 1, borderWidth: 0.3 },
  row: {  height: 28 ,borderWidth: 0.3  },
  text: { textAlign: 'center' }
});

**Comment by zuijiusi** [comment]
likes this 
![图片](https://user-images.githubusercontent.com/17403481/67925704-0d46a580-fbef-11e9-9452-e485f3e84eb9.png)

**Comment by tamir61** [comment]
Hey, is it possible to do it?
