### ISSUE TITLE
在ipone6 plus 和 ipone7 plus 出现适兼容性适配问题。

### ISSUE THREAD

**Issue by LiuShuoyu** [Gil2015/react-native-table-component#12]
你好， 在ipone6 plus 和 ipone7 plus 出现适兼容性适配问题。每个row 出现顶部的出现多余的样式。

<img width="308" alt="2017-09-23 10 51 08" src="https://user-images.githubusercontent.com/11488938/30774257-5f63194c-a0b2-11e7-98b5-bd2a787cc26c.png">

**Comment by Gil2015** [comment]
你好，刚看了下是开发环境下iphone plus系列都不支持borderWidth为0.5，真机暂时未遇到此问题，晚点我测试下，可以的话在组件里多做点设置。
暂时你可以先这么修改：
```jsx
  <Table borderStyle={{borderWidth: 1}}>
```

**Comment by Gil2015** [comment]
官方这个问题之后应该会修复，参考issue：https://github.com/facebook/react-native/issues/14106
暂时的解决方法是，plus系列要设置`borderWidth: 0.333`, 其他机型`borderWidth: 0.5`,如果是要上线产品的话需要判断下版本来设置，通用的做法是宽度先设置为整数
