### ISSUE TITLE
ViewPropTypes' is not supported in 'react-native-web' v12.0 onwards

### ISSUE THREAD

**Issue by markybry** [Gil2015/react-native-table-component#131]
If you upgrade to RNW 12.0 or greater you can no longer use react native web 

Error: ./node_modules/react-native-table-component/components/rows.js
Cannot find module: 'react-native-web/dist/exports/ViewPropTypes'. Make sure this package is installed.

**Comment by Dammic** [comment]
As I think this might not get fixed quickly, in the meantime I've prepared my own, slightly hacky workaround:
In ./scripts/fix-rn-web-proptypes-issue.sh:
```
#!/bin/bash

echo 'Fixing PropTypes issue related to react-native-table-component...'
for file in ./node_modules/react-native-table-component/components/*.js; do
    sed -i '/ViewPropTypes\.style/g' $file
    sed -i '/Text\.propTypes/g' $file
done
echo 'PropTypes issue fixed!'
```

And then in package.json:
```
scripts: {
    "postinstall": "sh ./scripts/fix-rn-web-proptypes-issue.sh"
}
```

The problem is just with propTypes, the rest appears to bo working fine.
