### ISSUE TITLE
Is it possible to freeze/sticky row?

### ISSUE THREAD

**Issue by ozergul** [Gil2015/react-native-table-component#133]
Hello, I wonder that it is possible to freeze/sticky row or rows. For example:

![image](https://user-images.githubusercontent.com/8460954/97450081-6270e080-1943-11eb-86e8-cd103e7b9a14.png)

**Comment by ZoharLiran** [comment]
your answer might be here:
https://github.com/Gil2015/react-native-table-component/issues/38
