### ISSUE TITLE
How to add numberOfLines for Cell component?

### ISSUE THREAD

**Issue by aliwaqar981** [Gil2015/react-native-table-component#142]
Hi! Thankyou for this great package. My text is too large to be fit in a cell. Although I want to display text which can be appeared in two lines and then .... . Just Like Text component. How can I do that?

### Current Behaviour
![Simulator Screen Shot - iPhone 12 - 2021-06-09 at 12 15 21](https://user-images.githubusercontent.com/43547698/121310059-5eb32c80-c91c-11eb-8a4f-53551c85b10b.png)

**Comment by mattslight** [comment]
I looked in the source code and the Cell component is a smart wrapper for `<Text ... />` so you can pass the standard text prop `numberOfLines` to Cell as
```
<Cell ...otherProps numberOfLines={1}>
```

**Comment by aliwaqar981** [comment]
Thanks @mattslight It seems like Cell props don't includes View props but numberOfLines is working fine
