### ISSUE TITLE
How can change table heading's font color separately ?

### ISSUE THREAD

**Issue by abdulhaque-ak** [Gil2015/react-native-table-component#149]
`<Row data={tableHead} widthArr={widthArr} style={styles.header} textStyle={styles.text} />`
`text: {
        textAlign: 'center',
        fontWeight: '100',
        fontFamily: 'Poppins-Regular',
        color: 'white'
}`

Here, textStyle is giving styles to whole texts. How can change color of headings separately ?

**Comment by dohooo** [comment]
Hey, I had rewrote it in typescript and I'll optimizing it in react-native-reanimated.  [react-native-reanimated-table](https://www.npmjs.com/package/react-native-reanimated-table) 🌴

BTW these problems are solved.
