### ISSUE TITLE
How to get the each column length when data is present in cell

### ISSUE THREAD

**Issue by mahesh963** [Gil2015/react-native-table-component#15]
Hi,
Guys i used the table module it's working great.
I want to get the column length that number of cells are filled with data in each column.
![screen shot 2017-10-06 at 6 24 25 pm](https://user-images.githubusercontent.com/20550553/31278806-193939c6-aac4-11e7-833d-089f4bafd42c.png)

Here I'm attaching the screen shot. i want to get the each column length if there is data(checked image) present in cell.can any one help to how the get the value.

**Comment by Gil2015** [comment]
The length of the column corresponds to the length of the data.If there is only one length of the array, there is only one column.
