### ISSUE TITLE
How to give touchable action for table head

### ISSUE THREAD

**Issue by mahesh963** [Gil2015/react-native-table-component#16]
Hi, guys how to give touchable action for table head to get the column value.
![screen shot 2017-10-10 at 3 32 23 pm](https://user-images.githubusercontent.com/20550553/31380864-49e06234-add0-11e7-9c02-bc89d1a3ea71.png)
while selecting on particular table head cell in each column.

**Comment by Gil2015** [comment]
I'm sorry I didn't encapsulate touchable action. U can do it like this
```js
<TableWrapper>
  {
    headData.map((cell, j) => (
      <TouchableOpacity key={j}  onPress={() => this._action()}>
        <Cell data={cell}/>
      </TouchableOpacity>
    ))
  }
</TableWrapper>
```
