### ISSUE TITLE
Use ViewStylePropTypes instead of ViewPropTypes.style

### ISSUE THREAD

**Issue by Lowisoft** [Gil2015/react-native-table-component#21]
Hi,
I've noticed that since the last update of the "react-native-table-component", I get following error "_undefined is not an object (evaluating '_reactNative.ViewPropTypes.style')_"

After some research, I've found out, that if you use "ViewStylePropTypes" instead of "ViewPropTypes.style", the error disappears.

So, please correct this mistake by importing "ViewStylePropTypes" from react-native and by replacing in your code every "ViewPropTypes.style" with "ViewStylePropTypes".

Thanks for your collaboration.

**Comment by Gil2015** [comment]
Hello, I see your advice,I'm my english is poor.
Is that your “react-native” version below 0.44?
Please use the vesion "^1.1.1" of “react-native-table-component ”, when the “react-native” version below 0.44.
