### ISSUE TITLE
表头是否可以固定

### ISSUE THREAD

**Issue by xuexiaoao** [Gil2015/react-native-table-component#24]
表头固定，下面的行可以滑动查看，类似下面这样
![image](https://user-images.githubusercontent.com/18185523/32825669-c4d8fe94-ca20-11e7-8a23-cec73340386a.png)

**Comment by Gil2015** [comment]
表头和表格主体分开，或者表头position，表格主体放到scrollview里

**Comment by xuexiaoao** [comment]
表头和表格主体分开，是指的各自用TableWrapper包裹放在table里面吗，我这么试过，实现不了我要的效果。。。。

**Comment by Gil2015** [comment]
之前有一个人和你一样的疑问，可以的应该。搞2个table或tablewraper，然后根据你原型图要求看表头定位在哪个元素里或位置上。表格内容嵌套到scrollview里实现滚动

**Comment by xuexiaoao** [comment]
好的，谢谢了

2017-11-16 13:56 GMT+08:00 鸡斯拉 <notifications@github.com>:
