### ISSUE TITLE
Zooming in on individual tables

### ISSUE THREAD

**Issue by BuilderX** [Gil2015/react-native-table-component#26]
Zooming in on individual table rows

**Comment by Gil2015** [comment]
Sorry，can you say something more about your question?

**Comment by BuilderX** [comment]
Sorry about that, I was using my mobile. I am running my application on an galaxy android  phone, I have tried to use the zoom (maximumZoomScale and minimumZoomScale) properties from a <Scrollview /> component that is wrapping my table.  But, I am unable to pinch and zoom in on  columns  and rows content to see my content closer.  Thank you.

**Comment by Gil2015** [comment]
The table component does not support scaling by itself. Is it useful if you add scaling properties to parent components.

**Comment by BuilderX** [comment]
Thank you for the reply.
