### ISSUE TITLE
fixed tableHead when scroll up down?

### ISSUE THREAD

**Issue by xuananpham93** [Gil2015/react-native-table-component#29]
Do you have any way to fixed table when scroll table, bro?

![screenshot_1515556711](https://user-images.githubusercontent.com/16789892/34755228-4691f828-f5f5-11e7-9a91-ed1ca3b11350.png)

**Comment by Gil2015** [comment]
You can render a large table with two table components. One is the header fixed, the other one is the scroll content of the body of the table.

**Comment by z5980000** [comment]
@xuananpham93 I think you can use animated and transform to fixed head. I have done this and worked perfectly.

**Comment by xuananpham93** [comment]
@z5980000, do you have an example for it?

**Comment by z5980000** [comment]
@xuananpham93 Yes, I am writting a component to accept data to render table with fixed columns and header.But now I have to do something else.

**Comment by LIZHIBIN513** [comment]
@xuananpham93  可以参考你固定表头的demo？ 谢谢

**Comment by LIZHIBIN513** [comment]
@Gil2015  怎样在 Example5 中添加固定表头功能（如果上下滑动，表头固定，左右滑动，最左侧固定）

**Comment by Gil2015** [comment]
@LIZHIBIN513 2边都能滑动而且头都能固定的话可能不行

**Comment by z5980000** [comment]
同时固定表头和左边某几列的我已经实现了，等我弄好贴代码

**Comment by LIZHIBIN513** [comment]
@z5980000  能不能先给我发一个啊  有点着急  465222498@qq.com  万分感谢！！！

**Comment by z5980000** [comment]
@LIZHIBIN513 已发邮件,不过因为是中间版本,可能会有什么问题,有问题随时联系吧

**Comment by LIZHIBIN513** [comment]
@z5980000  好的 十分感谢

**Comment by will86** [comment]
@z5980000  恰好我也有个固定左边一列和表格标题的需求，麻烦给发一份参考一下吧，will.zhang.sd@outlook.com   非常谢谢！

**Comment by vodanh109** [comment]
@z5980000 Can u pls send me your example to nmhung109@gmail.com? Thank you very much!

**Comment by xchunzhao** [comment]
@z5980000  Can u provide an example for fixing header and left column ?

**Comment by 417394980** [comment]
@z5980000 恰好我也有个固定左边一列和表格标题的需求，麻烦给发一份参考一下吧，417394980@qq.com 非常谢谢！非常谢谢！非常谢谢！

**Comment by lhaiqing** [comment]
@z5980000 固定左边一列和表格标题的demo麻烦发一份参考参考下，114991239@qq.com，感谢！🙏

**Comment by ashish2309** [comment]
class OrderHistoryScreen extends Component {

    setOrderInQueryForm(orderNumber) {
      this.props.updateQueryForm('order', orderNumber);
      Actions.contactUs();
    }

    render() {

        var tableData = [];
        var tableHead = ['Order No.', 'QTY', 'Cost', 'Contact Us'];
        for(let i = 0; i < this.props.orderData.length; i++) {
          var order = this.props.orderData[i];
          var tempArr = [];
          tempArr.push(<View><Text style={styles.orderNumText}>{order.orderNumber}</Text><Text>{moment(order.orderDate).format('llll')}</Text></View>);
          tempArr.push(order.totalQuantity);
          tempArr.push("₹ " + order.totalCost);
          tempArr.push(<View style={{alignItems  : 'center'}}>
            <TouchableOpacity onPress={this.setOrderInQueryForm.bind(this,order.orderNumber)} >
              <FontAwesomeIcon size={25} color="#24b5c8" icon={ faEnvelope } />
            </TouchableOpacity></View>);
          tableData.push(tempArr);
        }

        return (
          <View style = {styles.MainContainer}>
            <View style = {styles.header}><Text style={{fontSize : 20, color: 'white', backgroundColor: '#24b5c8'}}>Order History</Text></View>
            <View style={{alignSelf : 'stretch', marginTop : 5, flex: 1}}>
            <Table borderStyle={{borderWidth: 0.5, borderColor: '#dadada'}}>
              <Row flexArr={[2, 1, 1, 1.5]} data={tableHead} style={styles.head} textStyle={styles.headText}/>
            </Table>
            <ScrollView>
                <Table borderStyle={{borderWidth: 0.5, borderColor: '#dadada'}}>
                  <TableWrapper style={styles.wrapper}>
                    <Rows flexArr={[2, 1, 1, 1.5]} data={tableData} style={{backgroundColor: 'white'}} textStyle={styles.text}/>
                  </TableWrapper>
                </Table>
            </ScrollView>
            </View>
          </View>
        );
    }
}

const styles = StyleSheet.create({

    MainContainer : {
      flex: 1,
      flexDirection: 'column',
      alignItems: 'center',
      alignSelf : 'stretch'
    },
    header : {
      backgroundColor : '#24b5c8',
      paddingTop : 15,
      paddingBottom : 15,
      justifyContent : 'center',
      alignItems : 'center',
      elevation : 2,
      position : 'relative',
      alignSelf: 'stretch',
      marginTop : 2
    },
    head: { height: 40, backgroundColor: '#24b5c8', justifyContent : 'center' },
    headText : {color: 'white', textAlign : 'center'},
    text: { margin: 6 },
    wrapper: { flexDirection: 'row' },
    orderNumText : {
      fontWeight : 'bold',
      fontSize : 15,
      color : '#24b5c8',
      marginBottom : 10
    }
});

**Comment by H5futurehreohanshuo** [comment]
@z5980000 恰好我也有个固定左边一列和表格标题的需求，麻烦给发一份参考一下吧，18832643723@163.com 非常谢谢！非常谢谢！非常谢谢！

**Comment by gshoanganh** [comment]
can you update your code?

**Comment by gshoanganh** [comment]
> 同时固定表头和左边某几列的我已经实现了，等我弄好贴代码

my email: lequochoang@live.com
"Could you please send them to me?

**Comment by front-development** [comment]
@z5980000 恰好我也有个固定左边一列和表格标题的需求，麻烦给发一份参考一下吧，yifeng.ma@outlook.com 非常谢谢！非常谢谢！非常谢谢！

**Comment by dequal** [comment]
恰好我也有个固定左边一列和表格标题的需求，麻烦给发一份参考一下吧，806176940@qq.com 非常谢谢！非常谢谢！非常谢谢！
my email: ，806176940@qq.com
"Could you please send demo to me?

**Comment by front-development** [comment]
import React, { Component } from 'react';
import { StyleSheet, View, Dimensions, ScrollView } from 'react-native';
import { Table, Row, Rows, Col, TableWrapper } from 'react-native-table-component';

const ww = 130;

export default class ExampleOne extends Component {
    constructor(props) {
        super(props);
        this.state = {
        };
        this.headerIsScrolling = false;
        this.rowsIsScrolling = false;
    }

    // header头 10个
    genHeaderData = () => {
        const tableData = [];
        for (let i = 2; i <= 10; i += 1) {
            tableData.push(`header~(${i})`);
        }
        return [tableData];
    }

    // 左边的固定列 30个
    genColData = () => {
        const tableData = [];
        for (let i = 1; i <= 30; i += 1) {
            tableData.push(`Col~(${i})`);
        }
        return tableData;
    }

    // 生成列表右边数据项
    genRowsData = () => {
        const arr1 = [];
        const arr2 = [];
        for (let i = 2; i <= 10; i += 1) {
            arr1.push(`数据～(${i})`);
        }
        for (let j = 1; j <= 30; j += 1) {
            arr2.push(arr1);
        }
        return arr2;
    }

    render() {
        const state = this.state;

        return (
            <View style={styles.container}>
                <ScrollView>
                    <View style={{ flexDirection: 'row' }}>
                        <Table
                            borderStyle={{ borderWidth: 1, borderColor: '#c8e1ff' }}
                        >
                            <TableWrapper style={{ width: 130 }}>
                                <Col
                                    data={['header~(1)']}
                                    textStyle={styles.text}
                                    style={{ backgroundColor: '#537791' }}
                                    widthArr={[ww]}
                                    heightArr={[60]}
                                />
                            </TableWrapper>
                        </Table>
                        <ScrollView
                            horizontal
                            ref={(view) => { this.headerScrollView = view; }}
                            showsHorizontalScrollIndicator={false}
                            scrollEventThrottle={16}
                            onScroll={(event, x) => {
                                {
                                    console.log('rows水平滚动距离======>', event.nativeEvent);//水平滚动距离
                                    const offsetX = event.nativeEvent.contentOffset.x;
                                    if (!this.headerIsScrolling) {
                                        this.rowsIsScrolling = true;
                                        this.rowsScrollView.scrollTo({ x: offsetX });
                                    }
                                    this.headerIsScrolling = false;
                                }
                            }}
                        >
                            <Table borderStyle={{ borderWidth: 1, borderColor: '#c8e1ff' }}>
                                <Rows
                                    data={this.genHeaderData()}
                                    textStyle={styles.text}
                                    style={{ height: 60, backgroundColor: '#537791' }}
                                    widthArr={[ww, ww, ww, ww, ww, ww, ww, ww, ww]}
                                />
                            </Table>
                        </ScrollView>
                    </View>
                </ScrollView>
                <ScrollView>
                    <View style={{ flexDirection: 'row' }}>
                        <Table borderStyle={{ borderWidth: 1, borderColor: '#c8e1ff' }}>
                            <TableWrapper style={{ width: 130 }}>
                                <Col
                                    data={this.genColData()}
                                    textStyle={styles.text}
                                    heightArr={[40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40]}
                                />
                            </TableWrapper>
                        </Table>
                        <ScrollView
                            horizontal={true}
                            ref={(view) => { this.rowsScrollView = view; }}
                            scrollEventThrottle={16}
                            onScroll={(event) => {
                                {
                                    console.log('rows水平滚动距离======>', event.nativeEvent);//水平滚动距离
                                    const offsetX = event.nativeEvent.contentOffset.x;
                                    if (!this.rigthIsScrolling) {
                                        this.headerIsScrolling = true;
                                        this.headerScrollView.scrollTo({ x: offsetX });
                                    }
                                    this.rigthIsScrolling = false;
                                }
                            }}
                        >
                            <Table borderStyle={{ borderWidth: 1, borderColor: '#c8e1ff' }}>
                                <Rows
                                    data={this.genRowsData()}
                                    textStyle={styles.text}
                                    style={{ height: 40 }}
                                    widthArr={[ww, ww, ww, ww, ww, ww, ww, ww, ww]}
                                />
                            </Table>
                        </ScrollView>
                    </View>
                </ScrollView>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: { flex: 1, paddingTop: 130, backgroundColor: '#fff' },
    text: { margin: 6 },
});

**Comment by front-development** [comment]
有点性能问题，仅供参考

**Comment by sanghavan** [comment]
> import React, { Component } from 'react';
> import { StyleSheet, View, Dimensions, ScrollView } from 'react-native';
> import { Table, Row, Rows, Col, TableWrapper } from 'react-native-table-component';
> 
> const ww = 130;
> 
> export default class ExampleOne extends Component {
> constructor(props) {
> super(props);
> this.state = {
> };
> this.headerIsScrolling = false;
> this.rowsIsScrolling = false;
> }
> 
> ```
> // header头 10个
> genHeaderData = () => {
>     const tableData = [];
>     for (let i = 2; i <= 10; i += 1) {
>         tableData.push(`header~(${i})`);
>     }
>     return [tableData];
> }
> 
> // 左边的固定列 30个
> genColData = () => {
>     const tableData = [];
>     for (let i = 1; i <= 30; i += 1) {
>         tableData.push(`Col~(${i})`);
>     }
>     return tableData;
> }
> 
> // 生成列表右边数据项
> genRowsData = () => {
>     const arr1 = [];
>     const arr2 = [];
>     for (let i = 2; i <= 10; i += 1) {
>         arr1.push(`数据～(${i})`);
>     }
>     for (let j = 1; j <= 30; j += 1) {
>         arr2.push(arr1);
>     }
>     return arr2;
> }
> 
> render() {
>     const state = this.state;
> 
>     return (
>         <View style={styles.container}>
>             <ScrollView>
>                 <View style={{ flexDirection: 'row' }}>
>                     <Table
>                         borderStyle={{ borderWidth: 1, borderColor: '#c8e1ff' }}
>                     >
>                         <TableWrapper style={{ width: 130 }}>
>                             <Col
>                                 data={['header~(1)']}
>                                 textStyle={styles.text}
>                                 style={{ backgroundColor: '#537791' }}
>                                 widthArr={[ww]}
>                                 heightArr={[60]}
>                             />
>                         </TableWrapper>
>                     </Table>
>                     <ScrollView
>                         horizontal
>                         ref={(view) => { this.headerScrollView = view; }}
>                         showsHorizontalScrollIndicator={false}
>                         scrollEventThrottle={16}
>                         onScroll={(event, x) => {
>                             {
>                                 console.log('rows水平滚动距离======>', event.nativeEvent);//水平滚动距离
>                                 const offsetX = event.nativeEvent.contentOffset.x;
>                                 if (!this.headerIsScrolling) {
>                                     this.rowsIsScrolling = true;
>                                     this.rowsScrollView.scrollTo({ x: offsetX });
>                                 }
>                                 this.headerIsScrolling = false;
>                             }
>                         }}
>                     >
>                         <Table borderStyle={{ borderWidth: 1, borderColor: '#c8e1ff' }}>
>                             <Rows
>                                 data={this.genHeaderData()}
>                                 textStyle={styles.text}
>                                 style={{ height: 60, backgroundColor: '#537791' }}
>                                 widthArr={[ww, ww, ww, ww, ww, ww, ww, ww, ww]}
>                             />
>                         </Table>
>                     </ScrollView>
>                 </View>
>             </ScrollView>
>             <ScrollView>
>                 <View style={{ flexDirection: 'row' }}>
>                     <Table borderStyle={{ borderWidth: 1, borderColor: '#c8e1ff' }}>
>                         <TableWrapper style={{ width: 130 }}>
>                             <Col
>                                 data={this.genColData()}
>                                 textStyle={styles.text}
>                                 heightArr={[40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40]}
>                             />
>                         </TableWrapper>
>                     </Table>
>                     <ScrollView
>                         horizontal={true}
>                         ref={(view) => { this.rowsScrollView = view; }}
>                         scrollEventThrottle={16}
>                         onScroll={(event) => {
>                             {
>                                 console.log('rows水平滚动距离======>', event.nativeEvent);//水平滚动距离
>                                 const offsetX = event.nativeEvent.contentOffset.x;
>                                 if (!this.rigthIsScrolling) {
>                                     this.headerIsScrolling = true;
>                                     this.headerScrollView.scrollTo({ x: offsetX });
>                                 }
>                                 this.rigthIsScrolling = false;
>                             }
>                         }}
>                     >
>                         <Table borderStyle={{ borderWidth: 1, borderColor: '#c8e1ff' }}>
>                             <Rows
>                                 data={this.genRowsData()}
>                                 textStyle={styles.text}
>                                 style={{ height: 40 }}
>                                 widthArr={[ww, ww, ww, ww, ww, ww, ww, ww, ww]}
>                             />
>                         </Table>
>                     </ScrollView>
>                 </View>
>             </ScrollView>
>         </View>
>     );
> }
> ```
> 
> }
> 
> const styles = StyleSheet.create({
> container: { flex: 1, paddingTop: 130, backgroundColor: '#fff' },
> text: { margin: 6 },
> });

I just found the solution. Disable `scrollTo` animation
`this.scrollView.scrollTo({
  x: yourXValue,
  animated: false,
});`
Source: https://stackoverflow.com/questions/43338997/how-to-sync-two-scrollviews-in-react-native/43344011#43344011

**Comment by vicky335** [comment]
@z5980000 恰好我也有个固定左边一列和表格标题的需求，麻烦给发一份参考一下吧，29346258@qq.com 非常谢谢！非常谢谢！非常谢谢！
