### ISSUE TITLE
Conditional color text

### ISSUE THREAD

**Issue by RamosMicaela** [Gil2015/react-native-table-component#31]
Hello,
I'm using the component and I want to know if there is a way of change the text color depending on every row value.
Thanks!

**Comment by Gil2015** [comment]
You can refer to example 5 that how the background color changes

**Comment by RamosMicaela** [comment]
Yes, but I want the text color change if the number is > 7 for example.
Can I do that?

**Comment by Gil2015** [comment]
e: textStyle={[num > 7 && {color: 'your color'}]}

**Comment by RamosMicaela** [comment]
It works perfect! thank you so much!!!
