### ISSUE TITLE
Cell not rendering properly

### ISSUE THREAD

**Issue by ChenCodes** [Gil2015/react-native-table-component#33]
Hey there!

I noticed that one of the rows of my table stopped rendering cells correctly. 
<img width="337" alt="screen shot 2018-02-27 at 12 50 52 pm" src="https://user-images.githubusercontent.com/7213887/36754093-f4aa506c-1bbc-11e8-9eb8-1421be5cef74.png">
^When I did toggle inspector it showed that the cell had a height and width, but in the screenshot below that cell no longer has a height and width? 

<img width="321" alt="screen shot 2018-02-27 at 12 51 00 pm" src="https://user-images.githubusercontent.com/7213887/36754105-fa0eae72-1bbc-11e8-9b7c-3f51f1b0b5e6.png">

Any help would be appreciated!

**Comment by Gil2015** [comment]
Can you show me the code for this page，I try to find out the problem.

**Comment by ChenCodes** [comment]
Yes, I have cut down a lot of the other code but this is the foundation:

`import React from 'react'
import { TouchableOpacity, View, StyleSheet, Text } from 'react-native'
import { Table, Row, Cols } from 'react-native-table-component'

export class Table extends React.Component {
  render () {
    let tableHead = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight']
    let tableData = [
      ['col 1', 'col 1', 'col 1', 'col 1', 'col 1', 'col 1', 'col 1', 'col 1'],
      ['col 2', 'col 2', 'col 2', 'col 2', 'col 2', 'col 2', 'col 2', 'col 2'],
      ['col 3', 'col 3', 'col 3', 'col 3', 'col 3', 'col 3', 'col 3', 'col 3'],
      ['col 4', 'col 4', 'col 4', 'col 4', 'col 4', 'col 4', 'col 4', 'col 4'],
      ['col 5', 'col 5', 'col 5', 'col 5', 'col 5', 'col 5', 'col 5', 'col 5'],
      ['col 6', 'col 6', 'col 6', 'col 6', 'col 6', 'col 6', 'col 6', 'col 6'],
      ['col 7', 'col 7', 'col 7', 'col 7', 'col 7', 'col 7', 'col 7', 'col 7'],
      ['col 8', 'col 8', 'col 8', 'col 8', 'col 8', 'col 8', 'col 8', 'col 8'],
    ]

    return (
      <View>
        <Table style={styles.table} borderStyle={{borderWidth: 0.5, borderColor: '#526060'}}>
          <Row data={tableHead} style={styles.head} textStyle={styles.text} heightArr={Array(headerArray.length).fill(100)} widthArr={Array(headerArray.length).fill(150)} />
          <Cols data={tableData} textStyle={styles.text} heightArr={Array(headerArray.length).fill(100)} widthArr={Array(headerArray.length).fill(150)} />
        </Table>
      </View>
    )
  }
}

const styles = StyleSheet.create({
  table: { flex: 1 },
  head: { height: 100, backgroundColor: '#EDEDED' },
  text: { textAlign: 'center', padding: 15 },
})

export default Table
`

**Comment by Gil2015** [comment]
You try to delete this code.`table: { flex: 1 }`.
And you have set the height of row in styles.
So you don't need to set heightArr in the row label.

**Comment by ChenCodes** [comment]
Thanks for your help! It's good now.
