### ISSUE TITLE
Got an error while using property horizontal = {true}

### ISSUE THREAD

**Issue by harikanammi** [Gil2015/react-native-table-component#4]
I am running a sample app. In that i used Example 3 while using the scroll to entire Table and used horizontal ={true}.in Table View title columns and data columns got messed .please check the screenshot
![screen shot 2017-08-18 at 7 34 52 pm](https://user-images.githubusercontent.com/31063894/29462255-56ba7632-844c-11e7-9117-735c2ffee1ee.png) 
Any solutions can be appreciated

**Comment by Gil2015** [comment]
Could you show me your code?
