### ISSUE TITLE
No allowFontScaling props for row and rows

### ISSUE THREAD

**Issue by Kennytian** [Gil2015/react-native-table-component#42]
When I set 'Larger Text' on my Phone, so I can not use allowFontScaling props for Row and Rows component,   

![image](https://user-images.githubusercontent.com/2621619/38484011-a58a4732-3b9a-11e8-8bcb-d59d996af34b.png)

Text font size look it so large

![image](https://user-images.githubusercontent.com/2621619/38483961-6829662a-3b9a-11e8-8fa7-2084800f415e.png)

Look it better than no allowFontScaling

![image](https://user-images.githubusercontent.com/2621619/38484141-345626fc-3b9b-11e8-9f68-9e2c0b76aaf2.png)

![image](https://user-images.githubusercontent.com/2621619/38484198-6dcd0982-3b9b-11e8-9da2-70f6949af5aa.png)

So, I submit 2 PRs to you, please review it.
https://github.com/Gil2015/react-native-table-component/pull/40 
https://github.com/Gil2015/react-native-table-component/pull/41

**Comment by Kennytian** [comment]
@Gil2015  Wow, unbelievable response, so cool!  Wait for your new version release on npm

**Comment by Gil2015** [comment]
Thank you for your improvement ：）
