### ISSUE TITLE
为什么col或者cols无法做到高度自适应了？

### ISSUE THREAD

**Issue by xiao0502** [Gil2015/react-native-table-component#49]
如果无法做到自适应高度的话，那表格里面的内容就得限制的很死了，不能有多的文字或者其他内容作为表格内容了

**Comment by Gil2015** [comment]
col单列是可以自适应的，但是如果其中一个cell自适应后，该行的所有cell都要设法计算。因此推荐把数据转成适应row的格式

**Comment by xiao0502** [comment]
我的数据都是写展示型的文字，字数不限定的

**Comment by Gil2015** [comment]
那目前的解决方案的话只能建议把 数列数据数组 转换成 横列rows可用数组,抱歉
