### ISSUE TITLE
Some information

### ISSUE THREAD

**Issue by Angelk90** [Gil2015/react-native-table-component#51]
@Gil2015 : hi, congratulations on the module.
This is what I did as a test: https://snack.expo.io/B1CGUcV-7
I would like to be able to do something like in the image, is it possible?
 ![](https://i.imgur.com/sI9Wo2f.jpg)

**Comment by Gil2015** [comment]
This can be done, but the elements in the first and second columns need to add a high 1 px white bottom line to block the bottom edge of the cell.

**Comment by Gil2015** [comment]
You can refer to example 4

**Comment by Angelk90** [comment]
@Gil2015 : I tried to do as you say, but there are some things I can not do.
Link: https://snack.expo.io/SJkg0vS-7

the column size should not be different for each row, but it should have the maximum size you have in that column.
But I believe it can not be done.

Can you give me a hand to fix it?

**Comment by Gil2015** [comment]
```
constructor(props) {
    super(props);
    this.state = {
      tableHead: ['Gruppo A', '', 'G.', 'Diff.', 'Pti.'],
      tableData: [
        ['a', 'Russia', '1', '5', '3'],
        ['b', 'Uruguay', '1', '1', '3'],
        ['c', 'Egitto', '1', '-1', '0'],
        ['d', 'Arabia Saudita', '1', '-5', '0'],
      ],
    }
  }

  renderCellStyle(idx) {
    switch (idx) {
      case 0:
        return {
          flex: 2
        }
      case 1:
        return {
          flex: 4,
          borderBottomColor: '#ccc',
          borderBottomWidth: 1
        }
      default:
        return {
          flex: 1,
          borderBottomColor: '#ccc',
          borderBottomWidth: 1
        }
    }
  }

  render() {
    const state = this.state;
    const element = (data, index) => (
      <View style={styles.btnBox}>
        <View style={[styles.btn, {marginRight: 6}, index > 1 && {borderColor: 'transparent'}]}>
          <Text style={styles.btnText}>{index + 1}</Text>
        </View>
        <View style={styles.btn}>
          <Text style={styles.btnText}>{data}</Text>
        </View>
      </View>
    );
    
    return (
      <View style={styles.container}>
        <Table borderStyle={{borderColor: 'transparent'}}>
          <Row data={state.tableHead} style={styles.head} flexArr={[2,4,1,1,1]} textStyle={styles.text}/>
          {
            state.tableData.map((rowData, index) => (
              <TableWrapper key={index} style={styles.row}>
                {
                  rowData.map((cellData, cellIndex) => (
                    <Cell 
                      key={cellIndex} 
                      data={cellIndex === 0 ? element(cellData, index) : cellData} 
                      style={this.renderCellStyle(cellIndex)}
                      textStyle={styles.text}/>
                  ))
                }
              </TableWrapper>
            ))
          }
        </Table>
      </View>
    )
  }
```

<img src="https://raw.githubusercontent.com/Gil2015/tools_file/master/img/react-native-table-component/rn-table-component-example.png"/>

**Comment by Angelk90** [comment]
I thank you, last doubts.
1) I'm trying to recreate the rounded shadow / elevation effect in the table, but the results I get are very bad, can I apply it?
I get shelling in the sides.
2) How can I better center the text in the circle? 1,2,3,4 and a, b, c, d
3) There is a way to improve the circle, it seems to have some shells.
4) I pass you a version where I put the borderStyle = {{borderColor: '# 000'}}
to show you something strange happens in the tableHead.

Link: https: //snack.expo.io/HyOqZ98-7

**Comment by Gil2015** [comment]
Because you set up the style:marginLeft:10 of head.

**Comment by Angelk90** [comment]
@Gil2015 : Ok, I managed to fix it, for the points: 1,2,3
link: https://snack.expo.io/B1LR39P-m

**Comment by Gil2015** [comment]
The above problem is not a component problem
