### ISSUE TITLE
Doubts 

### ISSUE THREAD

**Issue by theapache64** [Gil2015/react-native-table-component#53]
Why use `TableWrapper` ?

**Comment by theapache64** [comment]
Is it possible to get auto-width for columns ?  I am getting my columns shrunken

![image](https://user-images.githubusercontent.com/9678279/41527491-fa3c202e-7304-11e8-89c0-05a0065457ad.png)

**Comment by theapache64** [comment]
Is there any way i can listen for `row` click ?

**Comment by Gil2015** [comment]
You can  also use the View instead of tableWrapper elements, their mutual effect is custom packaging complex table structure.
Using tableWrapper that we can make the structure more clearly, the second is can inherit the table component incoming border properties

**Comment by Gil2015** [comment]
I'm sorry that if you want adaptive widths, you need to use col or cols components, and the row and rows components can only handle high degree of adaptive.

**Comment by Gil2015** [comment]
You can set up a TouchableOpacity for row components to handle clicking events.

**Comment by theapache64** [comment]
Ok, so how do i get adaptive width using col and cols ? Is there any example available gil ?

**Comment by Gil2015** [comment]
You can refer to the tableData data structure and the final result of example 5. If you need the appropriate width, just do not set the width for Col and cols.

**Comment by theapache64** [comment]
I am sorry Gil. I ddn't get you. Could you please be more specific ?

**Comment by theapache64** [comment]
Gil, Is this library can handle any amount of data without break or stuck ?

**Comment by Gil2015** [comment]
[#54](https://github.com/Gil2015/react-native-table-component/issues/54)
