### ISSUE TITLE
data not rendering properly in cell

### ISSUE THREAD

**Issue by suhani-kohli** [Gil2015/react-native-table-component#55]
Since the data is long enough to fit in the width of the row it hides .
Example: data visible is 'Medical Off' although it is 'Medical Officer'
 What mistake am I committing or is there any way to fix it? 
I want the part that dosen't fit to be rendered on the next line within the cell.
 <img width="401" alt="screen shot 2018-07-05 at 12 51 46 am" src="https://user-images.githubusercontent.com/38916510/42292100-a7c2265e-7fed-11e8-955a-6c0a4b5d4e25.png">
<img width="561" alt="screen shot 2018-07-05 at 12 49 37 am" src="https://user-images.githubusercontent.com/38916510/42292104-afc3850a-7fed-11e8-8cbd-303640d23235.png">

**Comment by yeung108** [comment]
Same problem

**Comment by Gil2015** [comment]
If your rowstyle does not set the height attribute, the text will automatically wrap.
