### ISSUE TITLE
Module parse failed. Unexpected token

### ISSUE THREAD

**Issue by luongs3** [Gil2015/react-native-table-component#57]
I'm building an app with react-native and react-native-web (to reuse react native component on web). But i got this problem when building
```
Uncaught Error: Module parse failed: Unexpected token (8:75)
You may need an appropriate loader to handle this file type.
| class Row extends Component {
|   render() {
|     const {data, style, widthArr, height, flexArr, textStyle, borderStyle, ...props} = this.props;
|     let widthNum = 0;
|     if (widthArr) {
```
"react-native": "0.51.0"
"react": "^16.3.2",
"react-art": "^16.3.2",
"react-dom": "^16.3.2",
"react-native-web": "^0.8.4",
"react-native-table-component": "^1.1.8",
If you need more detail, please let me know. Thanks.

**Comment by Gil2015** [comment]
The mistake has told you that the eighth lines have grammatical errors

**Comment by luongs3** [comment]
yeah, this line, but can not find out
`const {data, style, widthArr, height, flexArr, textStyle, borderStyle, ...props} = this.props;`

**Comment by luongs3** [comment]
never mind, i solved the problem. Close here.
