### ISSUE TITLE
icon/image with data

### ISSUE THREAD

**Issue by h4m3d66** [Gil2015/react-native-table-component#58]
Hi,
Is it possible to add icon or image with rows data?

**Comment by Gil2015** [comment]
You can refer to example 4 or[issues51](https://github.com/Gil2015/react-native-table-component/issues/51)

**Comment by h4m3d66** [comment]
is it possible to make it more json friendly?

**Comment by Gil2015** [comment]
If that is done, it will not be very friendly to the expansion of table components.
