### ISSUE TITLE
Sortable headers for this component.

### ISSUE THREAD

**Issue by arkhamsushant** [Gil2015/react-native-table-component#60]
Hi, I have implemented and using this component in my production app, it works great. I need to know how do I have sortable headers in this component. Is there a javascript I can use for this purpose.

**Comment by Gil2015** [comment]
The component itself does not have a categorization function, so you can customize the cell component to add a categorization button, and then sort the tableData logically.

If the function is more complicated, I suggest using WebView to nested H5 form directly.
