### ISSUE TITLE
Table Rows not showing up when using FlexArr property

### ISSUE THREAD

**Issue by NewtonJoaquim** [Gil2015/react-native-table-component#61]
This is how the component looks like without using FlexArr
![image](https://user-images.githubusercontent.com/12428581/46744618-e040f100-cc81-11e8-9b73-ebce1d18276b.png)

And this is when i use flexArr
![image](https://user-images.githubusercontent.com/12428581/46744878-64937400-cc82-11e8-9b94-9eca5d9cddaa.png)

This is the code for the component:
`import React from 'react';
import {View, Text, TouchableOpacity, Dimensions} from 'react-native';
import {ListItem, Button, Icon} from 'react-native-elements';
import DatePicker from 'react-native-datepicker'
import { Table, TableWrapper, Row, Rows } from 'react-native-table-component';

import GLOBAL from '../styles/globalColors';
import data from '../data/extrato.json'

export default class FinanceiroView extends React.Component{

    studentList = this.props.navigation.state.params.students;
    extrato = data.extrato;

    state = {
        firstDate:null,
        secondDate:null,
        tableHead:["Data", "Movimento", "Valor", "Saldo"],
        tableData:[],
    };
  
    componentDidMount(){
        let tableContent = [];
        for(i=0; i<this.extrato.length; i++){
            let tableRow = [];
            tableRow.push(this.extrato[i].data)
            tableRow.push(this.extrato[i].movimento)
            tableRow.push(this.extrato[i].valor)
            tableRow.push(this.extrato[i].saldo)
            tableContent.push(tableRow);
        }
        this.setState({tableData:tableContent})
    }

    renderDrawerMenu(){
        const user = this.props.navigation.state.params.user;
        const token = this.props.navigation.state.params.token;

        //this.props.navigation.openDrawer({user, token, students, userid});
        this.props.navigation.navigate('Drawer', {user, token});
        this.props.navigation.openDrawer();
    }

    showDates(firstDate, secondDate){
        let firstSplit = firstDate.split('/');
        let secondSplit = secondDate.split('/');

        let first = new Date(firstSplit[2], firstSplit[1], firstSplit[0]);
        let second = new Date(secondSplit[2], secondSplit[1], secondSplit[0]);

        tableContent = []

        for (i=0;i<this.extrato.length;i++){
            let dateString = this.extrato[i].data.split('/');
            let date = new Date(dateString[2], dateString[1], dateString[0])

            if((date >= first) && (date <= second)){
                let tableRow = []
                tableRow.push(this.extrato[i].data)
                tableRow.push(this.extrato[i].movimento)
                tableRow.push(this.extrato[i].valor)
                tableRow.push(this.extrato[i].saldo)
                tableContent.push(tableRow);
            }
        }
        this.setState({tableData:tableContent})
    }

    render(){
        return(
                <View style={styles.container}>
                    <View style={{justifyContent:'flex-start', alignItems:'flex-start', padding:20}}>
                            <TouchableOpacity onPress={this.renderDrawerMenu.bind(this)}>
                                <Icon name='menu' color={GLOBAL.COLOR.SECONDARY} size={30}/>
                            </TouchableOpacity>
                        </View>   
                    <View style={{flexDirection:'row', backgroundColor:GLOBAL.COLOR.SECONDARY}}>
                    <DatePicker
                        style={{flex:1, marginTop:10, marginBottom:10}}
                        date={this.state.firstDate}
                        mode="date"
                        placeholder="De"
                        format="DD/MM/YYYY"
                                // minDate="2016-05-01"
                                // maxDate="2016-06-01"
                        confirmBtnText="Confirm"
                        cancelBtnText="Cancel"
                        showIcon={false}
                        customStyles={{
                        dateIcon: {
                            position: 'absolute',
                            left: 0,
                            top: 4,
                            marginLeft: 0
                        },
                        dateInput: {
                            marginLeft: 36,
                            backgroundColor:GLOBAL.COLOR.PRIMARY
                        },
                        dateTouchBody:{
                            color:GLOBAL.COLOR.SECONDARY
                        },
                        dateText:{
                            color:GLOBAL.COLOR.TEXT_COLOR,
                            fontSize:26
                        }
                        }}
                        onDateChange={(firstDate) => {
                            this.setState({firstDate: firstDate})
                            this.showDates(firstDate, this.state.secondDate)
                        }}
                    />

                    <DatePicker
                                style={{flex:1, marginRight:20, marginTop:10, marginBottom:10}}
                                date={this.state.secondDate}
                                mode="date"
                                placeholder="Até"
                                format="DD/MM/YYYY"
                                showIcon={false}
                                // minDate="2016-05-01"
                                // maxDate="2016-06-01"
                                confirmBtnText="Confirm"
                                cancelBtnText="Cancel"
                                customStyles={{
                                dateIcon: {
                                    position: 'absolute',
                                    left: 0,
                                    top: 4,
                                    marginLeft: 0
                                },
                                dateInput: {
                                    marginLeft: 36,
                                    backgroundColor:GLOBAL.COLOR.PRIMARY
                                },
                                dateTouchBody:{
                                    backgroundColor:GLOBAL.COLOR.SECONDARY
                                },
                                dateText:{
                                    color:GLOBAL.COLOR.TEXT_COLOR,
                                    fontSize:26
                                }
                                }}
                                onDateChange={(secondDate) => {
                                    this.setState({secondDate})
                                    this.showDates(this.state.firstDate, secondDate)
                                }}
                            />
                    </View>

                    <View>
                        <Table borderStyle={{borderWidth: 2, borderColor: GLOBAL.COLOR.PRIMARY}}>
                            <Row data={this.state.tableHead} flexArr={[2,2,1,1]} style={styles.head} textStyle={styles.tableHeadText}/>
                            <Rows data={this.state.tableData} flexArr={[2,2,1,1]} textStyle={styles.tableRowText}/>
                        </Table>
                    </View>
                </View>
        )
    }
}

const styles = {
    container:{
        flex:1,
        // justifyContent:'center',
        // alignItems:'center',
        backgroundColor:GLOBAL.COLOR.PRIMARY,
    },
    buttonContainer:{
        marginTop:10,
        flexDirection:'row',
        //flex:1
    },
    iconContainer:{
        flexDirection:'row',
        justifyContent:'flex-end',
        alignItems:'flex-end',
        padding:25,
        backgroundColor:GLOBAL.COLOR.PRIMARY
    },
    head:{
        height: 40, backgroundColor: GLOBAL.COLOR.SECONDARY 
    },
    tableHeadText:{
        fontSize:18,
        color:GLOBAL.COLOR.PRIMARY
    },
    tableRowText:{
        fontSize:18,
        color:GLOBAL.COLOR.SECONDARY
    }
};`

**Comment by Gil2015** [comment]
I've looked at your code and it doesn't seem to be a problem. You can try adding a height to the row or a height to the parent view of the table.
