### ISSUE TITLE
How to make one field of row bold and another fields normal

### ISSUE THREAD

**Issue by duha5h** [Gil2015/react-native-table-component#62]
Hello,

I have an table 
![image](https://user-images.githubusercontent.com/28962322/47413277-86a6ef00-d776-11e8-9b66-d93a9590ed75.png)

I want to make fontWeight: 'bold' for balance cells,, 
and for another  fontWeight should be normal.

I try 
`      textStyle={[index === 4 ? {fontWeight: 'bold'} : {fontWeight: 'normal'}]} 
`
but it is not working,, 
how I van do that??

**Comment by Gil2015** [comment]
This is OK. You can check where the problem is in your code.
