### ISSUE TITLE
Default Height for row

### ISSUE THREAD

**Issue by vwalletviettel** [Gil2015/react-native-table-component#65]
To my opinion, we better have props like default height for each row of column.
For ex: We have only one header, then rest of the row in this column are exactly same. So why should we have height for each element instead of default one for all of them.
==>Change in col.js:  const height = heightArr && heightArr[i] || this.props.defaultHeight;

**Comment by Gil2015** [comment]
Thank you for your advice. I'll consider making changes later.：）
