### ISSUE TITLE
如果为空的时候 table 能否给也显示一个空table

### ISSUE THREAD

**Issue by jahnli** [Gil2015/react-native-table-component#66]
如果当页面数据没加载出来  只会有一条线 能否显示成一个空table

**Comment by Gil2015** [comment]
这个优化我会在之后版本加进去，谢谢你的建议

**Comment by Gil2015** [comment]
考虑了下，觉得还是自己手动加个View在table里比较好，否者可能会增加过多的参数配置。

**Comment by jahnli** [comment]
好的，谢谢




| |
李佳衡
|
|
邮箱：jahnli@163.com
|

签名由 网易邮箱大师 定制

在2018年12月25日 20:47，鸡斯拉 写道：

Closed #66.
