### ISSUE TITLE
how to fix size on column in table component of react native

### ISSUE THREAD

**Issue by nuwwarah** [Gil2015/react-native-table-component#69]
![kejap](https://user-images.githubusercontent.com/43406022/50451690-6eb73b80-0970-11e9-855d-4a08c8af370e.png)

I code it like this:
![kejap2](https://user-images.githubusercontent.com/43406022/50451839-804d1300-0971-11e9-9c0e-70b5d6d8abfe.png)

 
How to fix this problem?

**Comment by Gil2015** [comment]
You can refer to the pattern in Example 2.
