### ISSUE TITLE
How we can freeze first column of table

### ISSUE THREAD

**Issue by jawadg** [Gil2015/react-native-table-component#70]
i want to freeze first column of table ,all columns scroll horizontally but first one remain freeze.

**Comment by Gil2015** [comment]
You can refer to the layout of Example 3.

**Comment by zhenghongkun** [comment]
> 您可以参考示例3的布局。

例3也不能冰洁列呀  我在这个冻结列上卡了很久，尝试了几种方法，都是性能很差而放弃

**Comment by zhenghongkun** [comment]
> 我想冻结表的第一列，所有列都水平滚动但第一列仍然冻结。

大兄弟，fiexd column 问题你解决了吗？
