### ISSUE TITLE
How would I freeze both the first row and first column?

### ISSUE THREAD

**Issue by jsochurek** [Gil2015/react-native-table-component#71]
Example 3 works great for freezing the first row, but I'm not sure if my case can be done using this library. Linking the scrollviews onScroll events is usually not a smooth solution, and that's the only way I can think of doing this

**Comment by BenjErgizerBunny** [comment]
@jsochurek did you ever figure this one out?

**Comment by ZoharLiran** [comment]
did you find a solution for this? I'm thinking about how to create this as well
