### ISSUE TITLE
Dynamic data in table

### ISSUE THREAD

**Issue by BenjErgizerBunny** [Gil2015/react-native-table-component#72]
How would you render dynamic data you get from an external API and therefore changes frequently to render in the table?  In all the examples I see its hardcoded.  I've tried creating an array of objects and passing that into the Row components data prop but it doesn't accept it in that format.

**Comment by Gil2015** [comment]
Are you just changing a value in an object, rather than assigning it to the whole object?

**Comment by iamir4g** [comment]
can you get example ??
