### ISSUE TITLE
Problem in IOS large screens

### ISSUE THREAD

**Issue by iraniamir** [Gil2015/react-native-table-component#8]
Hi, there
your component is very useful but in iphone plus each version and IOS tablets the table have problem, i think because ios scale the app it self. there is any way to fix it !!!?
thanks

**Comment by Gil2015** [comment]
Are there any images that can be used for example?Thanks.

**Comment by iraniamir** [comment]
i find the problem ios can't support borders with decimal numbers !!

**Comment by Gil2015** [comment]
You need to set the border option like this .
```js
<Table borderStyle={{borderWidth: 2}}></Table>
```

Use StyleSheet.hairlineWidth. It will give you a sharp line on all the devices.
```js
<Table borderStyle={{borderWidth: StyleSheet.hairlineWidth}}></Table>
```

If the number is float. you can set the width like this
```js
// iphone n
<Table borderStyle={{borderWidth: 1.5}}></Table>

// iphone n Plus
<Table borderStyle={{borderWidth: 1.333}}></Table>
```

[facebook/react-native#14106](facebook/react-native#14106)
