### ISSUE TITLE
Best way to add only inner borders?

### ISSUE THREAD

**Issue by luzushka** [Gil2015/react-native-table-component#80]
Hi,
I am trying to add a border radius to the table.
The only way I found is wrapping the table inside a View and style the view.

I need to remove the outside border but the ways I found are really verbose - many if/ternary statements.

I was wondering if there is a more elegant way to achieve this.

Thanks! :)

**Comment by Gil2015** [comment]
I'm not sure which border you ultimately want to hide. In addition to hiding the boundaries of each cell separately. You can also use view to draw a white line position over the border.

**Comment by luzushka** [comment]
I'm just trying to make the corners round...
