### ISSUE TITLE
How to fix first column and row like real table view?

### ISSUE THREAD

**Issue by nimeshbhalani** [Gil2015/react-native-table-component#83]
Like i am scroll horizontal with first column fix and scroll vertical with first row fix.

**Comment by Gil2015** [comment]
I'm sorry that the component itself does not implement this function

**Comment by bhaveshmalaviya** [comment]
I want to achieve the same functionality to fix first row and first column  while we scroll the table. Is there any other way we can achieve it? Thanks.

**Comment by abhishekemaster** [comment]
hello @bhaveshmalaviya have you achive that if so can you please help me
