### ISSUE TITLE
Remove table borders 

### ISSUE THREAD

**Issue by harikanammi** [Gil2015/react-native-table-component#9]
Hi,

I am using this module 
But I want to remove the all borders in my table view
How I can do that Here is my code:

  <Table style={styles.table}>

          {/* Right scrollview wraper */}
          <ScrollView horizontal={true}>

            <TableWraper>
              <Row data={this.state.tableHead} style={styles.head}  textStyle={styles.text}/>
              {
                this.state.tableData.map((data, i) => (
                  <TableWraper key={i}
                    style={[styles.row, i%2 && {backgroundColor: 'white'},i==0 && {backgroundColor: '#182e60', }]}>
                    {
                      data.map((cell,j) => (
                        i==0?(<TouchableOpacity key={j} style={styles.cell}
                            onPress={() =>  this._showData(data,i,j)}>
                           <Cell data={cell} textStyle={{
                           textAlign: 'center',
                           color: 'white'}}/>
                         </TouchableOpacity>)
                       :(<TouchableOpacity key={j} style={styles.cell}>
                         <Cell data={cell} textStyle={{
                         textAlign: 'center',
                         color: 'black'}}/>
                     </TouchableOpacity>)
                    )

                      )
                    }
                  </TableWraper>
                ))
              }
            </TableWraper>
          </ScrollView>
        </Table>

const styles = StyleSheet.create({
  table: { width: 360, flexDirection: 'row' },
  head: { backgroundColor: '#333', height: 40 },
  headText: { color: '#fff', textAlign: 'center' },
  titleText: { marginLeft: 6 },
  list: { height: 28, backgroundColor: '#f0f0f0' },
  listText: { textAlign: 'right', marginRight: 6 }
})

Here is the screenshot:

![screen shot 2017-08-31 at 10 57 23 am](https://user-images.githubusercontent.com/31063894/29907799-3c725792-8e3b-11e7-8f60-61b03e158106.png)

**Comment by Gil2015** [comment]
```jsx
<Table borderStyle={{borderColor: 'transparent'}}></Table>
```
or
```jsx
<TableWrapper borderStyle={{borderColor: 'transparent'}}></TableWrapper>
```
:)

**Comment by harikanammi** [comment]
It's working........... 
Thank you for your support
