### ISSUE TITLE
Using react-native-web

### ISSUE THREAD

**Issue by xiswar** [Gil2015/react-native-table-component#90]
Hello is there a way to make it work for react-native-web?

Installed:

    "react": "^16.5.1",
    "react-dom": "^16.5.1",
    "react-native-table-component": "^1.2.0",
    "react-native-web": "0.11.6",

dev:

    "babel-core": "^6.26.3",
    "babel-generator": "^6.26.1",
    "babel-plugin-react-native-web": "^0.8.9",
    "babel-preset-react-native": "^4.0.0",

Error:

node_modules/react-native-table-component/components/cell.js:5:19: This experimental syntax requires enabling the parser plugin: 'classProperties' (5:19)
```
  3 | 
  4 | export class Cell extends Component {
> 5 |   static propTypes = {
    |                   ^
  6 |     style: ViewPropTypes.style,
  7 |     textStyle: Text.propTypes.style,
  8 |     borderStyle: ViewPropTypes.style
```

I tried to install the plugin "classProperties" but my dependencies got messed up. 

Maybe someone has a working example?

**Comment by Gil2015** [comment]
I'm sorry, I haven't used react-native for a long time, and I don't have enough time to extend it.

**Comment by appbuildtest** [comment]
Any solution, please let us know.. same issue here..

**Comment by markybry** [comment]
I guess the simplest solution would be to remove reference to ViewPropTypes
