### ISSUE TITLE
Can't get rid of border

### ISSUE THREAD

**Issue by kceb** [Gil2015/react-native-table-component#95]
Hey thanks for the package, it's a real time saver.

I'm noticing that even when I set border to transparent, there seems to be a border. To remedy, I tried setting the width to 0, but there still seems to be a border that appears at random. Any idea what is causing this? Is it my emulator?

Issue: ![issue](https://cdn-std.dprcdn.net/files/acc_650298/UksZn0)

Notice the random white border/lines

Code:

```
        <Table borderStyle={{ borderWidth: 0, borderColor: 'transparent' }}>
          <Row style={{ height: 40, backgroundColor: '#808B97' }} data={state.tableHead} textStyle={{ margin: 6 }} />
        </Table>
        <ScrollView>
          <Table style={{ flex: 1 }} borderStyle={{ borderWidth: 0, borderColor: 'transparent' }}>
            {
              state.tableData.map((rowData, index) => (
                <TableWrapper key={index} style={{ flexDirection: 'row', backgroundColor: '#FFF1C1' }}>
                  {
                    rowData.map((cellData, cellIndex) => (
                      <Cell key={cellIndex} data={cellData} textStyle={{ margin: 6 }} />
                    ))
                  }
                </TableWrapper>
              ))
            }
          </Table>
        </ScrollView>
```

**Comment by imangerah** [comment]
Have a look at https://github.com/Gil2015/react-native-table-component/issues/96

Try setting a very small borderWidth as a workaround.

**Comment by Gil2015** [comment]
The default value of the borderWidth has been changed to 0 after version 1.2.1.
