### ISSUE TITLE
borderLeftWidth defaults to 1 when set to 0.

### ISSUE THREAD

**Issue by imangerah** [Gil2015/react-native-table-component#96]
https://github.com/Gil2015/react-native-table-component/blob/71ecf8f0cb329c98ac8000dc0f333cb29311d460/components/table.js#L21

Logic on L21 of table.js will default to 1 when explicitly set to 0 (since 0 is falsey). I have worked around this by setting a borderWidth of 0.00000001. Logic could be improved to:

`
    const borderLeftWidth = (borderStyle && borderStyle.borderWidth !== 'undefined') ? borderStyle.borderWidth  : 1;
`

Similar issue in cell.js, L20. May be related to https://github.com/Gil2015/react-native-table-component/issues/95

**Comment by Gil2015** [comment]
The default value of the borderWidth has been changed to 0 after version 1.2.1.
